version: '3.9'

services:
  database:
    container_name: database
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: raptix
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      TZ: Europe/Berlin
    ports:
      - '4306:3306'
    volumes:
      - ./.docker/mysql:/var/lib/mysql
  php:
    container_name: php
    build:
      dockerfile: .docker/php/Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    env_file:
      - ./.docker/.env
  webserver:
    container_name: webserver
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - database:database
    ports:
      - "8000:80"
    environment:
      PMA_HOST: database

  composer_installation:
    container_name: composer_installation
    image: composer
    volumes:
      - .:/app
    command: composer install --ignore-platform-reqs

  node:
    container_name: node
    image: node:16-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: yarn install
